# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
    - name: Setup .NET Core SDK 
      uses: actions/setup-dotnet@v1.7.2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3 
       with:
           # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x). Early access versions can be specified in the form of e.g. 14-ea, 14.0.0-ea, or 14.0.0-ea.28
           java-version: 
           # The package type (jre, jdk, jdk+fx)
           java-package: # optional, default is jdk
           # The architecture (x86, x64) of the package.
           architecture: # optional, default is x64
           # Path to where the compressed JDK is located. The path could be in your source repository or a local path on the agent.
           jdkFile: # optional
           # ID of the distributionManagement repository in the pom.xml file. Default is `github`
           server-id: # optional, default is github
           # Environment variable name for the username for authentication to the Apache Maven repository. Default is $GITHUB_ACTOR
           server-username: # optional, default is GITHUB_ACTOR
           # Environment variable name for password or token for authentication to the Apache Maven repository. Default is $GITHUB_TOKEN
           server-password: # optional, default is GITHUB_TOKEN
           # Path to where the settings.xml file will be written. Default is ~/.m2.
           settings-path: # optional
           # GPG private key to import. Default is empty string.
           gpg-private-key: # optional
           # Environment variable name for the GPG private key passphrase. Default is $GPG_PASSPHRASE.
           gpg-passphrase: # optional
